# Generated by Django 3.0.7 on 2020-10-16 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201016_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 8, 49, 51, 478908, tzinfo=utc)),
        ),
    ]
